// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8xOoneHaGicDY4zIpIK0nMHZwn5b7UjQ',
    appId: '1:52421058425:web:b200462b6fc3d717f1d9a8',
    messagingSenderId: '52421058425',
    projectId: 'ifelodun-mobile',
    authDomain: 'ifelodun-mobile.firebaseapp.com',
    storageBucket: 'ifelodun-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0P0E2UedEOJD9oiDl8jvpjz1GZEqyssU',
    appId: '1:52421058425:android:de39843f9a938a86f1d9a8',
    messagingSenderId: '52421058425',
    projectId: 'ifelodun-mobile',
    storageBucket: 'ifelodun-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX64fJoRPyqPfaXoz6kBvcfwu2CzEIcF0',
    appId: '1:52421058425:ios:d839ff27e02533b6f1d9a8',
    messagingSenderId: '52421058425',
    projectId: 'ifelodun-mobile',
    storageBucket: 'ifelodun-mobile.firebasestorage.app',
    iosBundleId: 'com.example.ifelodunAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX64fJoRPyqPfaXoz6kBvcfwu2CzEIcF0',
    appId: '1:52421058425:ios:d839ff27e02533b6f1d9a8',
    messagingSenderId: '52421058425',
    projectId: 'ifelodun-mobile',
    storageBucket: 'ifelodun-mobile.firebasestorage.app',
    iosBundleId: 'com.example.ifelodunAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8xOoneHaGicDY4zIpIK0nMHZwn5b7UjQ',
    appId: '1:52421058425:web:49b0434c2fbf309ef1d9a8',
    messagingSenderId: '52421058425',
    projectId: 'ifelodun-mobile',
    authDomain: 'ifelodun-mobile.firebaseapp.com',
    storageBucket: 'ifelodun-mobile.firebasestorage.app',
  );
}
